### ISSUE TITLE
Peer code review Leaderboard

### ISSUE THREAD

**Issue by nimplay** [shahira-sadat/Leaderboard#3]
the first part of the project look great. 
the items are adding correctly, and everything is ok

**Comment by wayungi** [comment]
### Appreciation
- You are very hardworking and highly motivated. Please keep this up.
### Suggested improvement
- innerHTML is a security vulnerability, please change it.

**Comment by shahira-sadat** [comment]
Thanks for your excellent recommendations and feedback.
